### PR TITLE
Rocky move repl

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Comment by 0xfaded** [comment]
LGTM. Could perhaps add some dummy members to the environment. I can do that next time I'm playing with that code.

**Comment by rocky** [comment]
> Could perhaps add some dummy members to the environment.

Sure. One member I'll add is a function results(i) that unwraps Results[i] from an interface if I knew how to do that. 

> I can do that next time I'm playing with that code.

Please do. But I'm hoping that you'll also create that better REPL.

**Comment by 0xfaded** [comment]
If results is a variable in the compiled interpreter,

```
env.Funcs["result"] = reflect.ValueOf(func(i int) interface{} { return results[i] })
```

would do the trick

**Comment by rocky** [comment]
Thanks! Will try out later..

**Pull request merged**
